//! DMG (Apple Disk Image / UDIF) detection and extraction tests.
//!
//! Fixtures are generated by `fixture_gen.sh` in this directory.
//! Run it on macOS: `cd tests/fixtures/dmg && bash fixture_gen.sh`

use exav_unpack::{detect, extract, Budget, Format, Limits};

const MARKER: &[u8] = b"hello hfs+";

fn fixture(name: &str) -> Vec<u8> {
    let p = format!("{}/tests/fixtures/dmg/{name}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read(&p).unwrap_or_else(|e| panic!("read {p}: {e}"))
}

fn contains_marker(entries: &[exav_unpack::Entry]) -> bool {
    entries
        .iter()
        .any(|e| e.data.windows(MARKER.len()).any(|w| w == MARKER))
}

// ---------------------------------------------------------------------------
// Detection
// ---------------------------------------------------------------------------

#[test]
fn detect_hfs_plus_udrw() {
    assert_eq!(detect(&fixture("hfs_plus_udrw.dmg")), Some(Format::Dmg));
}

#[test]
fn detect_hfs_plus_udzo() {
    assert_eq!(detect(&fixture("hfs_plus_udzo.dmg")), Some(Format::Dmg));
}

#[test]
fn detect_read_only() {
    assert_eq!(detect(&fixture("read_only.dmg")), Some(Format::Dmg));
}

#[test]
fn detect_encrypted() {
    assert_eq!(detect(&fixture("encrypted.dmg")), Some(Format::Dmg));
}

#[test]
fn detect_apfs_udrw() {
    assert_eq!(detect(&fixture("apfs_udrw.dmg")), Some(Format::Dmg));
}

#[test]
fn detect_apfs_readonly() {
    assert_eq!(detect(&fixture("apfs_readonly.dmg")), Some(Format::Dmg));
}

#[test]
fn detect_apfs_encrypted() {
    assert_eq!(detect(&fixture("apfs_encrypted.dmg")), Some(Format::Dmg));
}

// ---------------------------------------------------------------------------
// Extraction — HFS+
// ---------------------------------------------------------------------------

#[test]
fn extract_hfs_plus_udrw_finds_test_file() {
    let data = fixture("hfs_plus_udrw.dmg");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert!(!entries.is_empty());
    assert!(contains_marker(&entries));
}

#[test]
fn extract_hfs_plus_udzo_finds_test_file() {
    let data = fixture("hfs_plus_udzo.dmg");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert!(!entries.is_empty());
    assert!(contains_marker(&entries));
}

#[test]
fn extract_read_only_finds_test_file() {
    let data = fixture("read_only.dmg");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert!(!entries.is_empty());
    assert!(contains_marker(&entries));
}

// ---------------------------------------------------------------------------
// Extraction — Encrypted HFS+ with password
// ---------------------------------------------------------------------------

#[test]
fn extract_encrypted_no_password_reports_unsupported() {
    let data = fixture("encrypted.dmg");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert_eq!(entries.len(), 1);
    assert!(entries[0].unsupported.is_some());
    assert!(entries[0].encrypted);
}

#[test]
fn extract_encrypted_wrong_password_reports_unsupported() {
    let data = fixture("encrypted.dmg");
    let mut budget = Budget::with_passwords(Limits::default(), vec!["wrong".into()]);
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert_eq!(entries.len(), 1);
    assert!(entries[0].unsupported.is_some());
    assert!(entries[0].encrypted);
}

#[test]
fn extract_encrypted_correct_password_extracts_files() {
    let data = fixture("encrypted.dmg");
    let mut budget = Budget::with_passwords(Limits::default(), vec!["test123".into()]);
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert!(
        !entries.is_empty(),
        "should extract files from encrypted DMG"
    );
    assert!(contains_marker(&entries));
}

// ---------------------------------------------------------------------------
// Extraction — APFS
// ---------------------------------------------------------------------------

#[test]
fn extract_apfs_udrw_finds_test_file() {
    let data = fixture("apfs_udrw.dmg");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert!(!entries.is_empty());
    assert!(contains_marker(&entries));
}

#[test]
fn extract_apfs_readonly_finds_test_file() {
    let data = fixture("apfs_readonly.dmg");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert!(!entries.is_empty());
    assert!(contains_marker(&entries));
}

#[test]
fn extract_apfs_encrypted_no_password_reports_unsupported() {
    let data = fixture("apfs_encrypted.dmg");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert_eq!(entries.len(), 1);
    assert!(entries[0].unsupported.is_some());
    assert!(entries[0].encrypted);
}

#[test]
fn extract_apfs_encrypted_correct_password_extracts_files() {
    let data = fixture("apfs_encrypted.dmg");
    let mut budget = Budget::with_passwords(Limits::default(), vec!["test123".into()]);
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert!(!entries.is_empty());
    assert!(contains_marker(&entries));
}
