//! PDF parsing and encryption tests.
//!
//! Fixtures (under `test_data/pdf/`) are generated by the build/test scripts:
//! * `simple_unencrypted.pdf` — 1-page unencrypted
//! * `multipage_unencrypted.pdf` — 5-page unencrypted
//! * `aes128_encrypted.pdf` — AES-128 encrypted (user: user123, owner: owner456)
//! * `aes256_encrypted.pdf` — AES-256 encrypted (user: user123, owner: owner456)
//! * `rc4_40bit_encrypted.pdf` — RC4 40-bit encrypted (user: test, owner: owner)

use exav_unpack::{extract, Budget, Format, Limits};

fn fixture(name: &str) -> Vec<u8> {
    let p = format!("{}/test_data/pdf/{name}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read(&p).unwrap_or_else(|e| panic!("read {p}: {e}"))
}

/// Unencrypted PDF extracts successfully (returns entries, not an error).
#[test]
fn unencrypted_simple_pdf() {
    let blob = fixture("simple_unencrypted.pdf");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Pdf, &blob, &mut budget).unwrap();
    // Unencrypted PDF should not report encrypted
    assert!(
        entries.iter().all(|e| !e.encrypted),
        "unencrypted PDF entries should not be flagged encrypted"
    );
}

/// Multi-page unencrypted PDF extracts without errors.
#[test]
fn unencrypted_multipage_pdf() {
    let blob = fixture("multipage_unencrypted.pdf");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Pdf, &blob, &mut budget).unwrap();
    assert!(
        entries.iter().all(|e| !e.encrypted),
        "unencrypted multipage PDF entries should not be flagged encrypted"
    );
}

/// AES-128 encrypted PDF without password reports encrypted.
#[test]
fn aes128_encrypted_no_password() {
    let blob = fixture("aes128_encrypted.pdf");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Pdf, &blob, &mut budget).unwrap();
    eprintln!("entries: {entries:?}");
    assert!(
        entries.iter().any(|e| e.encrypted),
        "AES-128 encrypted PDF should be detected as encrypted without password, got {entries:?}"
    );
}

/// AES-256 encrypted PDF without password reports encrypted.
#[test]
fn aes256_encrypted_no_password() {
    let blob = fixture("aes256_encrypted.pdf");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Pdf, &blob, &mut budget).unwrap();
    assert!(
        entries.iter().any(|e| e.encrypted),
        "AES-256 encrypted PDF should be detected as encrypted without password"
    );
}

/// RC4 40-bit encrypted PDF without password reports encrypted.
#[test]
fn rc4_40bit_encrypted_no_password() {
    let blob = fixture("rc4_40bit_encrypted.pdf");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Pdf, &blob, &mut budget).unwrap();
    assert!(
        entries.iter().any(|e| e.encrypted),
        "RC4 40-bit encrypted PDF should be detected as encrypted without password"
    );
}

/// AES-128 encrypted PDF with correct user password decrypts (no error, not flagged encrypted).
#[test]
fn aes128_encrypted_with_password() {
    let blob = fixture("aes128_encrypted.pdf");
    let mut budget = Budget::with_passwords(Limits::default(), vec!["user123".to_string()]);
    let result = extract(Format::Pdf, &blob, &mut budget);
    // With the correct password, extraction should succeed without error
    // (blank pages have no streams, so entries may be empty)
    assert!(
        result.is_ok(),
        "AES-128 with password should not error: {result:?}"
    );
}

/// AES-256 encrypted PDF with correct user password decrypts (no error, not flagged encrypted).
#[test]
fn aes256_encrypted_with_password() {
    let blob = fixture("aes256_encrypted.pdf");
    let mut budget = Budget::with_passwords(Limits::default(), vec!["user123".to_string()]);
    let result = extract(Format::Pdf, &blob, &mut budget);
    assert!(
        result.is_ok(),
        "AES-256 with password should not error: {result:?}"
    );
}

/// RC4 40-bit encrypted PDF with correct user password decrypts (no error, not flagged encrypted).
#[test]
fn rc4_40bit_encrypted_with_password() {
    let blob = fixture("rc4_40bit_encrypted.pdf");
    let mut budget = Budget::with_passwords(Limits::default(), vec!["test".to_string()]);
    let result = extract(Format::Pdf, &blob, &mut budget);
    assert!(
        result.is_ok(),
        "RC4 40-bit with password should not error: {result:?}"
    );
}

/// Linearized PDF 1.4 (2 pages) extracts without errors.
#[test]
fn linearized_pdf() {
    let blob = fixture("linearized_2page.pdf");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Pdf, &blob, &mut budget).unwrap();
    assert!(
        entries.iter().all(|e| !e.encrypted),
        "linearized PDF should not be encrypted"
    );
}
