//! DMG (Apple Disk Image / UDIF) detection and extraction tests.
//!
//! Fixtures are generated by `fixture_gen.sh` in this directory.
//! Run it on macOS: `cd tests/fixtures/dmg && bash fixture_gen.sh`

use exav_unpack::{detect, extract, Budget, Format, Limits};

const MARKER: &[u8] = b"hello hfs+";

fn fixture(name: &str) -> Vec<u8> {
    let p = format!("{}/tests/fixtures/dmg/{name}", env!("CARGO_MANIFEST_DIR"));
    exav_unpack::read_fixture(&p).unwrap_or_else(|e| panic!("read {p}: {e}"))
}

fn contains_marker(entries: &[exav_unpack::Entry]) -> bool {
    entries
        .iter()
        .any(|e| e.data.windows(MARKER.len()).any(|w| w == MARKER))
}

/// Only the data fork is read, so a file with a resource fork, which is where
/// macOS keeps a compressed file's bytes, is reported rather than scanned as
/// though the data fork were all of it. The fixture's one file is given a
/// resource fork in its catalog record.
#[test]
fn a_file_with_a_resource_fork_is_reported() {
    let mut blob = fixture("hfs_plus_udrw.dmg");
    // The record's BSD info (owner 501, group 20, flags, mode 0o100644), 32
    // bytes into the record; the resource fork's logical size is 168 bytes in.
    let bsd = [0, 0, 1, 0xf5, 0, 0, 0, 0x14, 0, 0, 0x81, 0xa4];
    let at = blob
        .windows(bsd.len())
        .position(|w| w == bsd)
        .expect("the file's record");
    let size = at - 32 + 168;
    blob[size..size + 8].copy_from_slice(&100u64.to_be_bytes());
    let entries = extract(Format::Dmg, &blob, &mut Budget::new(Limits::default())).unwrap();
    let test = entries
        .iter()
        .find(|e| e.name.ends_with("test.txt"))
        .expect("the file");
    assert_eq!(test.unsupported, Some("HFS+ resource fork not read"));
}

/// A file whose data the image says is somewhere it cannot be read from is
/// reported, not left out: its first extent is moved far past the image.
#[test]
fn a_file_that_cannot_be_read_out_of_the_image_is_reported() {
    let mut blob = fixture("hfs_plus_udrw.dmg");
    let bsd = [0, 0, 1, 0xf5, 0, 0, 0, 0x14, 0, 0, 0x81, 0xa4];
    let at = blob
        .windows(bsd.len())
        .position(|w| w == bsd)
        .expect("the file's record");
    // The data fork's first extent: its start block, 104 bytes in.
    let start = at - 32 + 104;
    blob[start..start + 4].copy_from_slice(&0x00ff_ff00u32.to_be_bytes());
    let entries = extract(Format::Dmg, &blob, &mut Budget::new(Limits::default())).unwrap();
    let test = entries
        .iter()
        .find(|e| e.name.ends_with("test.txt"))
        .unwrap_or_else(|| panic!("left out: {:?}", entries.iter().map(|e| &e.name).collect::<Vec<_>>()));
    assert!(test.unsupported.is_some(), "read as {} bytes", test.data.len());
}

// ---------------------------------------------------------------------------
// Detection
// ---------------------------------------------------------------------------

#[test]
fn detect_hfs_plus_udrw() {
    assert_eq!(detect(&fixture("hfs_plus_udrw.dmg")), Some(Format::Dmg));
}

#[test]
fn detect_hfs_plus_udzo() {
    assert_eq!(detect(&fixture("hfs_plus_udzo.dmg")), Some(Format::Dmg));
}

#[test]
fn detect_read_only() {
    assert_eq!(detect(&fixture("read_only.dmg")), Some(Format::Dmg));
}

#[test]
fn detect_encrypted() {
    assert_eq!(detect(&fixture("encrypted.dmg")), Some(Format::Dmg));
}

#[test]
fn detect_apfs_udrw() {
    assert_eq!(detect(&fixture("apfs_udrw.dmg")), Some(Format::Dmg));
}

#[test]
fn detect_apfs_readonly() {
    assert_eq!(detect(&fixture("apfs_readonly.dmg")), Some(Format::Dmg));
}

#[test]
fn detect_apfs_encrypted() {
    assert_eq!(detect(&fixture("apfs_encrypted.dmg")), Some(Format::Dmg));
}

// ---------------------------------------------------------------------------
// Extraction — HFS+
// ---------------------------------------------------------------------------

#[test]
fn extract_hfs_plus_udrw_finds_test_file() {
    let data = fixture("hfs_plus_udrw.dmg");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert!(!entries.is_empty());
    assert!(contains_marker(&entries));
}

#[test]
fn extract_hfs_plus_udzo_finds_test_file() {
    let data = fixture("hfs_plus_udzo.dmg");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert!(!entries.is_empty());
    assert!(contains_marker(&entries));
}

#[test]
fn extract_read_only_finds_test_file() {
    let data = fixture("read_only.dmg");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert!(!entries.is_empty());
    assert!(contains_marker(&entries));
}

// ---------------------------------------------------------------------------
// Extraction — Encrypted HFS+ with password
// ---------------------------------------------------------------------------

#[test]
fn extract_encrypted_no_password_reports_unsupported() {
    let data = fixture("encrypted.dmg");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert_eq!(entries.len(), 1);
    assert!(entries[0].unsupported.is_some());
    assert!(entries[0].encrypted);
}

#[test]
fn extract_encrypted_wrong_password_reports_unsupported() {
    let data = fixture("encrypted.dmg");
    let mut budget = Budget::with_passwords(Limits::default(), vec!["wrong".into()]);
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert_eq!(entries.len(), 1);
    assert!(entries[0].unsupported.is_some());
    assert!(entries[0].encrypted);
}

#[cfg(feature = "decrypt")]
#[test]
fn extract_encrypted_correct_password_extracts_files() {
    let data = fixture("encrypted.dmg");
    let mut budget = Budget::with_passwords(Limits::default(), vec!["test123".into()]);
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert!(
        !entries.is_empty(),
        "should extract files from encrypted DMG"
    );
    assert!(contains_marker(&entries));
}

// ---------------------------------------------------------------------------
// Extraction — APFS
// ---------------------------------------------------------------------------

#[test]
fn extract_apfs_udrw_finds_test_file() {
    let data = fixture("apfs_udrw.dmg");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert!(!entries.is_empty());
    assert!(contains_marker(&entries));
}

#[test]
fn extract_apfs_readonly_finds_test_file() {
    let data = fixture("apfs_readonly.dmg");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert!(!entries.is_empty());
    assert!(contains_marker(&entries));
}

#[test]
fn extract_apfs_encrypted_no_password_reports_unsupported() {
    let data = fixture("apfs_encrypted.dmg");
    let mut budget = Budget::new(Limits::default());
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert_eq!(entries.len(), 1);
    assert!(entries[0].unsupported.is_some());
    assert!(entries[0].encrypted);
}

#[cfg(feature = "decrypt")]
#[test]
fn extract_apfs_encrypted_correct_password_extracts_files() {
    let data = fixture("apfs_encrypted.dmg");
    let mut budget = Budget::with_passwords(Limits::default(), vec!["test123".into()]);
    let entries = extract(Format::Dmg, &data, &mut budget).unwrap();
    assert!(!entries.is_empty());
    assert!(contains_marker(&entries));
}
