#!/usr/bin/env bash
# Point the build at LLD, which ships inside the Rust toolchain as `rust-lld`.
#
# Why: every `tests/*.rs` is its own crate, statically linked against the whole
# dependency graph. Linking — not compiling — is what makes a full test run slow
# here. Measured on this workspace: 4024 ms -> 871 ms to relink one test binary.
#
# This GENERATES `.cargo/config.toml` (gitignored) because both paths involved
# are machine-specific: rustup's install location, and the linker search dir.
# A relative `-B` does not work — cargo runs build scripts from a different
# working directory, so the path must be absolute. Without the generated config
# the build still works; it just uses the system linker.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
host="$(rustc -vV | sed -n 's/^host: //p')"
lld="$(rustc --print sysroot)/lib/rustlib/$host/bin/rust-lld"
[ -x "$lld" ] || { echo "rust-lld not found at $lld" >&2; exit 1; }

dir="$root/.cargo/lld"
mkdir -p "$dir"
# `cc -fuse-ld=NAME` resolves NAME on the linker search path and will not take an
# absolute path, so give it a correctly-named symlink to find.
ln -sf "$lld" "$dir/ld.lld"

cat > "$root/.cargo/config.toml" <<CONF
# GENERATED by scripts/setup-lld.sh — do not edit, and do not commit.
# Re-run that script after changing toolchains.
[target.$host]
rustflags = ["-C", "link-arg=-B$dir", "-C", "link-arg=-fuse-ld=lld"]
CONF
echo "wrote $root/.cargo/config.toml using $lld"
